language: python
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install pip --upgrade
  - pip install codecov
install:
  - pip install -e .[tests]
script: pytest --cov
after_success:
  - codecov
